"""add total_copies to books

Revision ID: 7ab7f7022796
Revises: 82b62866b1b3
Create Date: 2025-11-13 06:12:19.500382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ab7f7022796'
down_revision: Union[str, Sequence[str], None] = '82b62866b1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('total_copies', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'total_copies')
    # ### end Alembic commands ###
